os:
  - osx

language: node_js

node_js:
  - "node"

before_script: ./script/travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change